Controllers/ClienteController.cs
using AgenciaDeViagens.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgenciaDeViagens.Controllers
{
    public class ClienteController : Controller
    {
        private Context _context;

        public ClienteController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cliente = _context.Cliente.ToList();

            return View(cliente);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            _context.Add(cliente);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null)
                return NotFound();

            var cliente = _context.Cliente.SingleOrDefault(a => a.Id == id);

            if (cliente == null)
                return NotFound();

            return View(cliente);

        }

        [HttpPost]
        public IActionResult Edit(int id, Cliente cliente)
        {
            if (id != cliente.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Update(cliente);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cliente);
        }

        public IActionResult Delete(int id)
        {
            if (id == null)
                return NotFound();

            var cliente = _context.Cliente.SingleOrDefault(a => a.Id == id);

            if (cliente == null)
                return NotFound();

            return View(cliente);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            var cliente = _context.Cliente.SingleOrDefault(a => a.Id == id);

            if (cliente == null)
                return NotFound();

            _context.Remove(cliente);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            if (id == null)
                return NotFound();

            var cliente = _context.Cliente.SingleOrDefault(a => a.Id == id);

            if (cliente == null)
                return NotFound();

            return View(cliente);
        }

       

    }
}

Controllers/DestinoController.cs
using AgenciaDeViagens.Models;
using Microsoft.AspNetCore.Mvc;

namespace AgenciaDeViagens.Controllers
{
    public class DestinoController : Controller
    {
        private Context _context;

        public DestinoController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var destino = _context.Destino.ToList();
            return View(destino);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Destino destino)
        {
            _context.Add(destino);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null)
                return NotFound();

            var destino = _context.Destino.SingleOrDefault(a => a.Id == id);

            if (destino == null)
                return NotFound();

            return View(destino);

        }

        [HttpPost]
        public IActionResult Edit(int id, Destino destino)
        {
            if (id != destino.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Update(destino);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(destino);
        }

        public IActionResult Delete(int id)
        {
            if (id == null)
                return NotFound();

            var destino = _context.Destino.SingleOrDefault(a => a.Id == id);

            if (destino == null)
                return NotFound();

            return View(destino);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            var destino = _context.Destino.SingleOrDefault(a => a.Id == id);

            if (destino == null)
                return NotFound();

            _context.Remove(destino);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            if (id == null)
                return NotFound();

            var destino = _context.Destino.SingleOrDefault(a => a.Id == id);

            if (destino == null)
                return NotFound();

            return View(destino);
        }
    }
}

Controllers/ViagemController.cs
using Microsoft.AspNetCore.Mvc;
using AgenciaDeViagens.Models;

namespace AgenciaDeViagens.Controllers
{
    public class ViagemController : Controller
    {
        private Context _context;
        public ViagemController(Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var viagem = _context.Viagem.ToList();
            return View(viagem);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Viagem viagem)
        {
            _context.Add(viagem);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null)
                return NotFound();

            var viagem = _context.Viagem.SingleOrDefault(a => a.Id == id);

            if (viagem == null)
                return NotFound();

            return View(viagem);

        }

        [HttpPost]
        public IActionResult Edit(int id, Viagem viagem)
        {
            if (id != viagem.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Update(viagem);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(viagem);
        }

        public IActionResult Delete(int id)
        {
            if (id == null)
                return NotFound();

            var viagem = _context.Viagem.SingleOrDefault(a => a.Id == id);

            if (viagem == null)
                return NotFound();

            return View(viagem);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            var viagem = _context.Viagem.SingleOrDefault(a => a.Id == id);

            if (viagem == null)
                return NotFound();

            _context.Remove(viagem);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VariGUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgenciaDeViagens.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-nav border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><big>VariGUI</big><small> Airlines</small></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between bg-nav"> 
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Destino" asp-action="Index">Destinos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Viagem" asp-action="Index">Viagens</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-nav">
        <div class="container text-white">
            &copy; 2021 - VariGUI Airlines
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>